main: io.github.logics4.individualkeepinventory_b1_7_3.IKI
name: ${project.name}
authors: ["Logics4"]
version: ${project.version}
description: ${project.description}

permissions:
  iki.events.playerdeath.keepinventory:
    default: false
